const { MongoClient } = require("mongodb");

const mongoUrl = process.env.MONGO_URL || "mongodb://mongodb:27017/phase2";
const dbName = process.env.DB_NAME || "phase2";
const pollIntervalMs = Number(process.env.POLL_INTERVAL_MS || 3000);
const demoMode = process.env.DEMO_MODE !== "false";
const openAiApiKey = process.env.OPENAI_API_KEY;
const openAiModel = process.env.OPENAI_MODEL || "gpt-4o-mini";

let jobs;

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function createDemoResponse(prompt) {
  return [
    "Demo mode response:",
    `You asked: "${prompt}"`,
    "This response was generated by the worker container without calling an external API.",
    "The important Docker concept is that this text was saved back into MongoDB by a different container.",
  ].join("\n");
}

async function callOpenAi(prompt) {
  if (demoMode || !openAiApiKey) {
    return createDemoResponse(prompt);
  }

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${openAiApiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: openAiModel,
      messages: [
        {
          role: "system",
          content:
            "You are a helpful assistant for a Docker lab. Keep answers concise and educational.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `OpenAI API request failed with status ${response.status}: ${errorText}`,
    );
  }

  const data = await response.json();
  return data.choices[0].message.content;
}

async function claimNextJob() {
  return jobs.findOneAndUpdate(
    { status: "queued" },
    {
      $set: {
        status: "processing",
        updatedAt: new Date(),
      },
    },
    {
      sort: { createdAt: 1 },
      returnDocument: "after",
      includeResultMetadata: false,
    },
  );
}

async function processJob(job) {
  console.log(`Processing job ${job._id}`);

  try {
    const response = await callOpenAi(job.prompt);

    await jobs.updateOne(
      { _id: job._id },
      {
        $set: {
          status: "completed",
          response,
          error: null,
          updatedAt: new Date(),
        },
      },
    );

    console.log(`Completed job ${job._id}`);
  } catch (error) {
    await jobs.updateOne(
      { _id: job._id },
      {
        $set: {
          status: "failed",
          response: null,
          error: error.message,
          updatedAt: new Date(),
        },
      },
    );

    console.error(`Failed job ${job._id}:`, error.message);
  }
}

async function workLoop() {
  while (true) {
    const job = await claimNextJob();

    if (job) {
      await processJob(job);
    } else {
      await sleep(pollIntervalMs);
    }
  }
}

async function start() {
  const client = new MongoClient(mongoUrl);
  await client.connect();

  const db = client.db(dbName);
  jobs = db.collection("jobs");
  await jobs.createIndex({ status: 1, createdAt: 1 });

  console.log(`Worker connected to MongoDB database "${dbName}"`);
  console.log(`Worker demo mode: ${demoMode}`);
  console.log(`Worker polling every ${pollIntervalMs} ms`);

  await workLoop();
}

start().catch((error) => {
  console.error("Worker failed:", error);
  process.exit(1);
});
